config/routes.rb
Rails.application.routes.draw do
  root 'orders#index'

  resources :orders, only: %i(new create update) do
    put :update_shipment_status, on: :collection
  end

  resources :purchase_orders, only: %i(index show update destroy)
  resources :invoices, only: %i(index show)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  	self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :orders
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base

  has_many :orders, ->{where type: Order::PUBLIC_TYPE}
  has_many :order_details, through: :orders
  has_many :invoice_details, dependent: :destroy

  before_validation :generate_invoice_code, on: :create

  acts_as_paranoid

  private
  def generate_invoice_code
    record = true
    while record
      random = Array.new(9){rand(9)}.join
      record = Invoice.where(invoice_code: random).exists?
    end
    self.invoice_code = random if invoice_code.blank?
  end
end

app/models/invoice_detail.rb
class InvoiceDetail < ActiveRecord::Base
	belongs_to :invoice
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :company
	has_many :order_details, dependent: :destroy
	accepts_nested_attributes_for :order_details, allow_destroy: true
	accepts_nested_attributes_for :company
	acts_as_paranoid

	after_initialize { order_details.build unless self.persisted? || order_details.present? }
	before_create :calculate_order_price
	before_create :set_tax_price
	before_create :set_total_price
	before_update :calculate_order_price
	after_update :update_price, :update_postage_price, :update_tax_price, :update_total_price, on: :update


	ORDER_HISTORY_PARAMS = [:name, :postage, :company_id, :invoice_id, order_details_attributes: [:id, :order_id, :product_name, :quantity, :_destroy, :unit_price]]

	SUPPLIER_UPDATE_PARAMS = [:is_public, :postage, :created_at, :company_id, :tax_price, :delivery_at, order_details_attributes: [:id, :product_name, :_destroy, :unit_price, :quantity]]

    UPDATE_ORDER_STATUS = [:order_status,:updated_at]

	validates :name, presence: true
	validates :company_id, presence: true


	def select_order_status
	    case order_status
	    when "not_deliver"
	      [translate("not_deliver"), translate("in_progress"), translate("already_deliver")]
	    when "in_progress"
	      [translate("not_deliver"), translate("in_progress"), translate("already_deliver")]
	    when "already_deliver"
	      [translate("in_progress"), translate("already_deliver"), translate("recieved_products")]
	    when "recieved_products"
	      [translate("recieved_products"), translate("already_deliver")]
	    end
	end

	def translate order_status
    	[I18n.t("activerecord.order.order_status.#{order_status}"), order_status]
  	end


	private

	def calculate_order_price
	   order_details.each(&:calculate_order_detail_price)
	   self.price = order_details.map(&:price).sum
	end


	def set_tax_price
		if self.postage.blank?
			self.postage = 0
		end
		tmp_total_price = self.price + self.postage

	    self.tax_price = (tmp_total_price * 0.08)
	end

	def set_total_price
	    self.total_price = self.price + self.tax_price + self.postage
	end


	def update_price
		# debugコード
		puts "price_update******************************"
		order_details.each do |order|
			p order.price
		end
	    price = order_details.sum(:price)
	    update_columns price: price
	end

	def update_postage_price
	    update_columns postage: postage
	end

	def update_tax_price
		tmp_total_price = price + postage
	    update_columns tax_price: (tmp_total_price * 0.08)
	end

	def update_total_price
		tmp_total_price = price + postage + tax_price
	    update_columns total_price: tmp_total_price
	end


	def generate_invoice_code
	    random = Random.new
		random.rand(1..6)
	end
end

app/models/order_detail.rb
# Table name: order_details # 注文明細
#
#  id           :integer          not null, primary key
#  order_id     :integer          not null              # 注文ID
#  product_name :string           not null              # 商品名
#  unit_price   :integer          not null              # 単価
#  quantity     :integer          not null              # 数量
#  created_at   :datetime         not null
#  updated_at   :datetime         not null

class OrderDetail < ActiveRecord::Base
	belongs_to :order
	#accepts_nested_attributes_for :order
	acts_as_paranoid

	validates :product_name, presence: true
	validates :unit_price, presence: true, numericality: {only_integer: true}, length: {maximum: 10}
	validates :quantity, presence: true, length: {maximum: 10}
	validates :quantity, numericality: {greater_than_or_eq: 0}
	validates :quantity, numericality: {greater_than: 0}


	# 合計金額を計算する
	def calculate_order_detail_price
	   	self.price = unit_price * quantity
	rescue
	    self.price = 0
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

	# 請求書一覧
	def index
		# sum→合計金額、count→注文数
	    @invoices = Order.group(:company_id).select("*, sum(orders.total_price) as total_invoice_price,count(orders.id) as count").paginate(page: params[:page], per_page: 10).includes(:company).to_a
	end

	# 請求書詳細
	def show
    	@company = Company.find(params[:id])
    	@invoices = Order.where(company_id: params[:id]).to_a
    	@invoices_prices = Order.select("*, sum(orders.total_price) as invoice_all_price, sum(orders.postage) as total_invoice_postage,sum(orders.tax_price) as total_invoice_tax_price, sum(orders.price) as total_invoice_price").where(company_id: params[:id]).to_a
	end
end

app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.paginate(page: params[:page], per_page: 20)
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
  	@order =  Order.new
  end

  # 発注書作成
  def create
  	# input data
  	@order = Order.new(order_params)
  	# 保存
  	if @order.save
  		#success
      flash[:success] = "発注書を作成したよ！注文一覧を確認してみてね！"
  		redirect_to new_order_path
  	else
  		#falied
  		render :new
  	end
  end

  # 配送状況の更新
  #def update
  #  @order = Order.find_by id: params[:id]
  #  respond_to do |format|
  #    if @order.update params[:orders][:order_status]
  #    #if @order.public_send params[:orders][:order_status]
  #      format.json do
  #        render json: {id: @order.id, order_status: @order.order_status, selectbox: @order.select_order_status}
  #      end
  #    else
  #      format.json{render json: {errors: @order.errors.full_messages}}
  #    end
  #  end
  #end

  private

    def order_params
      params.require(:order).permit(Order::ORDER_HISTORY_PARAMS).merge order_status: "not_deliver", is_public: true
    end

    def status_params
      params.require(:order).permit(Order::UPDATE_ORDER_STATUS)
    end

end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController

	# 注文書一覧
	def index
	    @purchase_orders = Order.order(created_at: :desc).paginate(page: params[:page], per_page: 10).includes(:company).to_a
	end

	def show
		@order_history = Order.find(params[:id])
		company = @order_history.company
	end

	# 注文書：更新する
	def update
	    @restaurant_order = Order.find_by id: params[:id]
	    respond_to do |format|
	      if @restaurant_order.update purchase_params

	        format.html{redirect_to purchase_order_path(@restaurant_order)}
	      else
	        format.html{redirect_to purchase_order_path(@restaurant_order)}
	      end
	      #format.js{render layout: false}
	      format.html { render :nothing => true }
	    end
	end

	# 注文書：削除
	def destroy
	    @order = Order.find_by(id: params[:id])
	    @order.destroy
	    redirect_to purchase_orders_path
	end

	private
	def purchase_params
	    params.require(:order).permit(Order::SUPPLIER_UPDATE_PARAMS)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	# ページごとの完全なタイトルを返します。
	def full_title(page_title = '')
	    base_title = "簡易注文システム_(:3」∠)_"
	    if page_title.empty?
	      base_title
	    else
	      page_title + " | " + base_title
	    end
	end

	# 商品削除機能（ゴミ箱アイコン）
	def link_to_remove_fields name, f, class_name
	    f.hidden_field(:_destroy, value: 0) + link_to(name, "javascript:void(0)",
	      class: "delete delete_order_detail #{class_name}")
	end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/order_detail_helper.rb
module OrderDetailHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/views/invoices/_invoice_detail.html.slim
- @invoices.each do |invoice|
  li.o-table__head__flex.fn-each-invoice-list#invoice_list data-invoice-id="#{invoice.company_id}" data-href="#{invoice_path(invoice.company_id)}"
    .o-table__data__invoice = "##{invoice.company.id}"
    .o-table__data__invoice = invoice.company.name
    .o-table__data__invoice#index-invoice-price &yen#{number_with_delimiter invoice.total_invoice_price}
    .o-table__data__invoice = invoice.count
    .o-table__data__invoice = l Date.parse(invoice.updated_at.to_s)
    .o-table__data__invoice 2019/7/31

app/views/invoices/_invoice_list.html.slim
section.invoice-index

	.o-table
	- if @invoices.any?
      	.o-table__inner
          	ul.no-padding-mergin
	            li.o-table__head__flex
	              .o-table__invoiceLabel 請求番号
	              .o-table__invoiceLabel 取引先名
	              .o-table__invoiceLabel
	                = "注文金額(税込)"
	              .o-table__invoiceLabel 注文数
	              .o-table__invoiceLabel 発行日
	              .o-table__invoiceLabel 支払期限
				.resources_data_list
					= render "invoice_detail"
	- else
      	.o-table__blank
        	h2 請求書がないよ！
        	p まずは発注書を作成してみようね！



javascript:
	$(function() {

	    $(this).find('li').click( function() {
	    	var href_link = $(this).attr('id');
	    	if (href_link == 'invoice_list') {
				window.location = $(this).attr('data-href');
	    	}
	    });

	});

app/views/invoices/index.html.slim
- provide(:title, "請求書一覧")

h1 請求書一覧

.row

	= will_paginate

	= render 'invoice_list'

	= will_paginate

app/views/invoices/show.html.slim
- provide(:title, "請求書詳細")

.row

  section#fn-invoice-detail.p-invoiceDetail
    .md-table01-box
        .md-table01-header-flex-inner
          .md-table01-back-wrap
            = link_to '請求書一覧', invoices_path
        .md-invoice01-box
          .md-invoices01-wrap
            .md-invoice01-ttl-box
              h1 請求書
              .md-invoice01-left-box
                h3
                  | 〒#{@company.zipcode1}-#{@company.zipcode2}
                  br
                  | #{@company.state}#{@company.city}#{@company.address}#{@company.address2}
                h2 #{@company.name} 御中
                p 下記の通りご請求申し上げます。
                dl.ex-sub
                  dt.ex-sub
                    span 請求番号
                  dd.ex-sub
                    span.js-update-invoice-code #{@company.id}-201906
                dl.ex-sub.ex-right
                  dt.ex-sub
                    span 発行日
                  dd.ex-sub
                    span
                      | 2019/06/10
                dl
                  dt.ex-sum
                    span 合計金額
                    span
                      | (税込)
                  - @invoices_prices.each do |invoice_price|
                    dd
                      span.f26 &yen#{number_with_delimiter invoice_price.invoice_all_price}
                dl
                  dt
                    span 支払期限
                  dd
                    span.invoice_expires_at
                      | 2019/7/31
                dl
                  dt
                    span 請求対象
                  dd
                    span
                      | 2019年6月分(2019/06/01 ~ 2019/06/30)

                dl
                  dt
                    span 振込先
                  dd
                    span
                      | りそな銀行　虎ノ門支店　株式会社ANTI HERO SK
                    br
                      |（普通）699543
              .md-invoice01-right-box
                dl
                  dt
                    | 販売元
                  dd
                    ul
                      li.f15 株式会社ANTI HERO SK
                      li 〒153-0051
                      li 東京都港区虎ノ門虎ノ門ヒルズ 2-1-3
                      li TEL：03-6412-8683
                      li MAIL：anti-hero-sk@gmail.com
                dl
                  dt
                    | 請求元
                  dd
                    ul
                      li.f15 株式会社ANTI HERO SK
                      li 〒153-0051
                      li 東京都港区虎ノ門虎ノ門ヒルズ 2-1-3
                      li TEL：03-6412-8683
                      li MAIL：anti-hero-sk@gmail.com
            .md-invoice01-table-box#js-invoice-table-by-order style="display: block"
                table.md-invoice01-table-by-order
                  thead
                    tr
                      th
                        | 注文日
                      th
                        | 商品名
                      th
                        | 価格(税抜)
                      th
                        | 数量
                      th
                        | 小計(税抜)
                  tbody
                  - @invoices.each do |invoice|
                    - invoice.order_details.each do |detail|
                      tr
                        td
                          | #{l detail.created_at, format: '%Y/%m/%d' }
                        td
                          | #{detail.product_name}
                        td
                          | &yen#{number_with_delimiter detail.unit_price}
                        td
                          | #{detail.quantity}
                          - detail_price = detail.unit_price * detail.quantity
                        td
                          | &yen#{number_with_delimiter detail_price}
                    tr
                      td
                      td
                        | 送料
                      td
                      td
                      td
                        | &yen#{number_with_delimiter invoice.postage}
            - @invoices_prices.each do |invoice_price|
              .md-invoice01-table-bottom-box
                  dl
                    dt
                      | 小計
                    dd
                      | &yen#{number_with_delimiter invoice_price.total_invoice_price}
                  dl
                    dt
                      | 送料合計
                    dd
                      | &yen#{number_with_delimiter invoice_price.total_invoice_postage}
                  dl
                    dt
                      | 消費税
                    dd
                      | &yen#{number_with_delimiter invoice_price.total_invoice_tax_price.to_i}
                  dl
                    dt.ex-sum 合計
                    dd.ex-sum &yen#{number_with_delimiter invoice_price.invoice_all_price}
            .md-invoice01-table-bottom-box
              .md-invoice01-bottom-comment
               p ※#{@company.name}様 発注分

app/views/layouts/_footer.html.slim
footer.footer

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to "簡易注文システム_(:3」∠)_", root_path, id: "logo"
    p#company_name for 株式会社ANTI HERO SK
    nav
      ul.nav.navbar-nav.navbar-right
      	li
          = link_to "注文書作成", new_order_path
        li
          = link_to "注文一覧", purchase_orders_path
        li
          = link_to "請求書一覧", invoices_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
      = yield
      = render 'layouts/footer'
      /= debug(params) if Rails.env.development?

app/views/orders/_form.html.slim
= form_for(@order, url: orders_path) do |f|
	= render 'shared/error_messages',  object: f.object

	.md-table01-box-inner
        table.md-table01-single
          thead
            tr
              th
                | 取引先名
          tbody
            tr
              td.single-field
              	= f.collection_select :company_id, Company.order(id: :asc), :id, :name, {prompt: "選択してください"}

	.md-table01-box-inner
        table.md-table01-single
          thead
            tr
              th
                | 受注名称
          tbody
            tr
              td.single-field
                = f.text_field :name, class: 'form-control'


	.md-table01-box-inner
	    .md-table01-body-wrap.ex-gray
	      table
	        thead
	          tr
	            th.ex-width-40
	              | 商品名
	            th.ex-width-26
	              | 単価
	            th.ex-width-26
	              | 数量
	            th.ex-width-24-fix
	    .md-table01-body-wrap
		       table#product_list.resources_data_list
		        tbody
					= f.fields_for :order_details, @order.order_details.build do |od|
	            		= render 'order_detail_fields', f:od
		.md-table01-box-inner.no-border.text-right
		    = link_to_add_association "商品を追加", f, :order_details, class: 'btn btn-add',data: { association_insertion_node: "#product_list",association_insertion_method: "append" }

	.md-table01-box-inner
        table.md-table01-single
          thead
            tr
              th
                | 送料
          tbody
            tr#md-restaurant-postage
              td.single-field
                = f.text_field :postage, class: "form-control postage"



	.submit_button
		= f.submit yield(:button_text), class: "btn btn-primary"

app/views/orders/index.html.slim
.center.jumbotron
    p ようこそ、株式会社ANTI HERO SK 様
    h1
      | まずは注文書を作成してね！

	= link_to "作成する", new_order_path, class: "btn btn-lg btn-primary"

app/views/orders/new.html.slim
- provide(:title, "注文書作成")
- provide(:button_text, '登録')

h1
  | 注文書作成

.row
	div
		= render 'form'

app/views/purchase_orders/_form.html.slim
.wrapper.-gray
  table.-noborderTop
    thead
      tr
        th._widthPercent40
          | 商品名
        th._widthPercent25
          | 単価(税抜)
        th._widthPercent35
          | 数量

.wrapper.md-table01-input-table.o-tableDetail__selectBoxInner
  table.-noborderTop#product_list.resources_data_list
    = f.fields_for :order_details, f.object.order_details do |b|
        = render "order_detail_fields", f: b
.wrapper.md-table01-box-inner.no-border.text-right
    = link_to_add_association "商品を追加", f, :order_details, class: 'btn btn-add',data: { association_insertion_node: "#product_list",association_insertion_method: "append" }

app/views/purchase_orders/_order_detail_fields.html.slim
tr.nested-fields
  td.ex-width-30
    = f.text_field :product_name, class: "form-control"
  td.ex-width-30
    = f.text_field :unit_price, class: "form-control price-order-detail ex-price"
  td.ex-width-30
    = f.text_field :quantity, class: "form-control quantity-order-detail"
  td.ex-width-24-fix.ex-txt-right
    = link_to_remove_association '削除', f, class: 'btn btn-default'

app/views/purchase_orders/_purchase_histories.html.slim
- @purchase_orders.each do |order_history|
  li.-purchaseOrderHistory#purchase_order_list data-order-id="#{order_history.id}" data-href="purchase_orders/#{order_history.id}" data-order-code="#{order_history.id}" class="o-table__head__flex"
    .o-table__data__flex
      | ##{order_history.id}
    .o-table__data__flex
      = order_history.created_at.strftime('%Y/%m/%d %H:%M')
    .o-table__data__flex = order_history.company.name
    .o-table__data__flex = order_history.name
    .o-table__data__flex
      | &yen#{number_with_delimiter order_history.total_price}

app/views/purchase_orders/_purchase_orders.html.slim
section.p-purchase-order-histories-index

	.o-table
	- if @purchase_orders.any?
      	.o-table__inner
          	ul.no-padding-mergin
	            li.o-table__head__flex
	              .o-table__flexLabel 注文番号
	              .o-table__flexLabel.-second 注文日
	              .o-table__flexLabel　取引先名
	              .o-table__flexLabel　注文名称
	              .o-table__flexLabel
	                = "注文金額(税込)"
				.resources_data_list
					= render "purchase_histories"
	- else
      	.o-table__blank
        	h2 注文書がないよ！
        	p まずは発注書を作成してみようね！



javascript:
	$(function() {

	    $(this).find('li').click( function() {
	    	var href_link = $(this).attr('id');
	    	if (href_link == 'purchase_order_list') {
				window.location = $(this).attr('data-href');
	    	}
	    });

	});

app/views/purchase_orders/_search_form.html.slim
= search_form_for @q do |f|
	= f.label :company_name_cont, '取引先名検索'
	.input-group
		= f.text_field :company_name_cont, placeholder: "取引先名", class: 'form-control'
		span.input-group-btn
			= f.submit '検索', class: "btn btn-primary"

app/views/purchase_orders/index.html.slim
- provide(:title, "注文書一覧")

h1 注文書一覧

.row
	/.search_form
		= render 'search_form'

	= will_paginate

	= render "purchase_orders"

	= will_paginate

app/views/purchase_orders/show.html.slim
- can_edit_order = 1

- provide(:title, "注文詳細")

h1 注文詳細

.row
	section
	  .o-tableDetail.p-detail#fn-supplier-edit-order data-restaurant-id="#{@order_history.company_id}" data-order-id="#{@order_history.id}" data-status="#{@order_history.order_status}"
	  	= form_for @order_history, url: purchase_order_path(@order_history), html: {id: "form_order_history"}, remote: true do |f|
	      .o-tableDetail__head
	        .m-headRight
	          ul
	              li.right
	                span#edit-purchase-order 編集する
	        .m-headLeft.return
	        	= fa_icon "angle-double-left"
	          	= link_to "一覧へ戻る", purchase_orders_path

	      .o-tableDetail__box#js-show-history-header
	        table
	          tbody
	            tr
	              th
	                | 注文日
	              td
	                | #{l @order_history.created_at}
	            tr
	              th
	                | 納品希望日
	              td#fn-read-deliverdate
	                - if @order_history.delivery_at
	                  | #{l @order_history.delivery_at, format: :too_short}
	                - else
	                  | 指定なし
	              td.date-pick#fn-edit-deliverdate style="display: none"
	                = f.text_field :delivery_at, value: @order_history.delivery_at.nil? ? "指定なし" : (l @order_history.delivery_at),
	                    class: "datepick mdl-textfield__input md-order-datepick", id: "fn-select-date", readonly: "readonly"
	            tr
	              th
	                | 注文番号
	              td
	                | ##{@order_history.id}

	            tr
	              th
	                | 注文名称
	              td
	                | #{@order_history.name}
	            /tr
	              th
	                | 配送状況
	              td#fn-edit-order_status-show-page
	              	span.tableSelect = f.select :order_status, options_for_select(@order_history.select_order_status, @order_history.order_status),
	                    {}, {id: "fn-supplier-select-order-status"}
	                /- if (@order_history.invoice.present? && @order_history.invoice.is_send?)
	                  = @order_history.translated_order_status
	                /- else
	                  span.tableSelect = f.select :order_status, options_for_select(@order_history.select_order_status, @order_history.order_status),
	                    {}, {id: "fn-supplier-select-order-status"}
	            tr
	                  th
	                    | 請求月
	                  td
	                    | 2019年6月
	            tr
	              th
	                | 納品先店舗
	              td
	                = @order_history.company.name
	            tr
	              th
	                | 納品先住所
	              td
	                | 〒#{@order_history.company.zipcode1}-#{@order_history.company.zipcode2}
	                | #{@order_history.company.state}#{@order_history.company.city}
	                | #{@order_history.company.address} #{@order_history.company.address2}
	            tr
	              th
	                | 納品先電話番号
	              td
	                | #{@order_history.company.tel}
	      .o-tableDetail__boxInner#order_details_history_list
	        .wrapper.-gray
	          table
	            thead
	              th.col-2 商品名
	              th.col-3 単価(税抜)
	              th.col-3 数量
	        .wrapper
	          table.resources_data_list.ex-no-topborder
	            tbody
	              - @order_history.order_details.each do |detail|
	                tr
	                  td.col-2 = detail.product_name
	                  td.col-3 &yen#{number_with_delimiter detail.unit_price}
	                  td.col-3 = detail.quantity
	      .o-tableDetail__boxInner#order-price
	        .wrapper
	          table.-single
	            thead
	              tr
	                th
	                  | 小計(税抜)
	                th
	                  | 送料(税抜)
	                th
	                  | 消費税
	                th
	                  | 注文金額合計(税込)
	            tbody
	              tr
	                td &yen#{number_with_delimiter @order_history.price}
	                td
	                  | &yen#{number_with_delimiter @order_history.postage.to_i}
	                td &yen#{number_with_delimiter @order_history.tax_price}
	                td
	                  | &yen#{number_with_delimiter @order_history.total_price}

	      - if can_edit_order
	        #edit-purchase-order-history style="display: none;"
	          .o-tableDetail__boxInner.md-table01-box-inner
	            /= render "partials/errors_message", resource: @order_history
	            = render 'shared/error_messages',  object: f.object
	            = render "form", f: f
	          .o-tableDetail__boxInner
	            .wrapper
	              table.-single.resources_data_list
	                thead
	                  tr
	                    th
	                      | 小計(税抜)
	                    th
	                      | 送料(税抜)
	                    th
	                      | 消費税
	                    th
	                      | 注文金額合計(税抜)
	                tbody
	                  tr
	                    td &yen#{number_with_delimiter @order_history.price}
	                    td.postage-field
	                      = fa_icon "fa-yen-sign"
	                      = f.text_field :postage, class: "postage"
	                    td.order-tax-price
	                      | &yen#{number_with_delimiter @order_history.tax_price.to_i}
	                      span
	                    td
	                      | &yen#{number_with_delimiter @order_history.total_price + (@order_history.postage.to_i * 0.08).to_i}

	      - if can_edit_order

	      	.o-tableSubmit#edit-purchase-order-button style="display: none;"
	            .o-tableSubmit__recordSubmit
	              = submit_tag "保存", class: "ex-active-save ex-gold"
	              = link_to "キャンセル", purchase_orders_path, class: "ex-active-cancel ex-gold"
	        .o-tableDetail__bottomLink
	          p.removeButton#fn-remove-button
	            | 注文を削除する
	    #fn-confirm-remove.mfp-hide
	      .o-popUp
	        p.title
	        	| 注文を削除してよろしいですか？
	        .btn
	          span#confirm_no
	            p.ex-anwerno いいえ
	          span#confirm_yes
	            = link_to "はい", purchase_order_path(@order_history), method: :delete, class: "md-remove-button"
	    #fn-confirm-update-status-show-page.mfp-hide
	      .o-popUp#fn-confirm
	        p.title#popup_text
	        .btn
	          span#confirm_no
	            p.ex-anwerno いいえ
	          span#confirm_yes
	            = button_to "はい", order_path(@order_history.id), {form_class: "fn-update-order-status"}
	      .o-popUp.-shipment#fn-success style="display: none;"
	        .success
	          i.fa.fa-check-circle
	          | 配送状況を変更しました！
	      .o-popUp.-shipmentul#js-orderErrorFailTransaction-text style="display:none;color:red;"

javascript:

	// 編集ボタン
	$(document).on("click", "#edit-purchase-order", function(){
	  $("#order_details_history_list").hide();
	  $("#order-price").hide();
	  $("#edit-purchase-order-history").show();
	  $("#edit-purchase-order").addClass("md-none-edit-button");
	  $("#edit-purchase-order").removeClass("md-edit-button");
	  $("#edit-purchase-order-button").show();
	  $("#fn-read-deliverdate").hide();
	  $("#fn-edit-deliverdate").show();
	});

	// カレンダー
	$(document).on("ready page:load", function(){
	  selectDate.init();
	});

	var selectDate = {
	  constructor: {
	    trigger: "#fn-select-date",
	  },
	  init: function(){
	    var self = this;
	    self.pickDate();
	  },
	  pickDate: function(){
	    var self = this;
	    var constructor = self.constructor;
	    $(constructor.trigger).datepicker({
	      altFormat: "yy/mm/dd",
	      autoclose: true,
	      changeMonth: true,
	      changeYear: true,
	      minDate: 0,
	      showButtonPanel : true,
	      buttonImage: "http://www.freeiconspng.com/uploads/calendar-icon-business-3.png",
		  buttonText: "選択",
		  buttonImageOnly: true,
		  showOn: "button"
	    });

	    var old_fn = $.datepicker._updateDatepicker;
		$.datepicker._updateDatepicker = function(inst) {
		    old_fn.call(this, inst);
		    var buttonPane = $(this).datepicker("widget").find(".ui-datepicker-buttonpane");
		    var buttonHtml = "<button type='button' class='ui-datepicker-clean ui-state-default ui-priority-primary ui-corner-all'>クリア</button>";
		    $(buttonHtml).appendTo(buttonPane).click(
		      function(ev) {
		        $.datepicker._clearDate(inst.input);
		        $(constructor.trigger).val("指定なし");
		    });
		}
	  }
	}

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
	ul
	  - object.errors.full_messages.each do |msg|
	    li
          i.fa.fa-exclamation-circle
          = msg


- if object.errors.any?
	javascript:

			$(document).ready(function() {
				 var path = location.pathname
				 if (path == '/orders') {
					history.pushState('', '', location.href + '/new');
				 }
			});